(function(root,factory){"use strict";const api=factory(root);if(typeof module==="object"&&module.exports)module.exports=factory;if(root)root.Cfr05CloudCuttingFiles=api;})(typeof globalThis!=="undefined"?globalThis:this,function(root){
  "use strict";
  const MAX_FILE_SIZE_BYTES=50*1024*1024;
  const TYPES=Object.freeze({dxf:["application/dxf","application/x-dxf","text/plain"],ord:["application/octet-stream","text/plain"],omx:["application/octet-stream","text/plain"]});
  const UPLOAD_ROLES=Object.freeze(["owner","admin","operator"]),READ_ROLES=Object.freeze([...UPLOAD_ROLES,"viewer"]);
  const STAGES=Object.freeze(["preflight","membership_validation","job_validation","local_file_validation","sha256_calculation","immutable_path_creation","storage_upload","uploaded_metadata_verification","firestore_metadata_creation","final_verification","completed"]);
  const exactKeys=(v,keys)=>v&&typeof v==="object"&&!Array.isArray(v)&&Object.keys(v).every(k=>keys.includes(k));
  const errorInfo=e=>({code:String(e?.code||""),message:String(e?.message||e||"Unknown error")});
  const definite=e=>e?.indeterminate!==true && !/unknown|timeout|network/i.test(String(e?.code||"")+" "+String(e?.message||""));
  function safeResult(value){if(!value)return null;return JSON.parse(JSON.stringify(value,(key,item)=>/url|token|content|blob|buffer/i.test(key)?undefined:item));}
  function createSessionGates(){let firestore=false,rules=false;return Object.freeze({configureOperatorSession(value={}){firestore=value.firestoreMembershipWriteProtectionConfirmed===true;rules=value.productionRulesConfirmedDeployed===true;return this.get();},clear(){firestore=false;rules=false;return this.get();},get(){return Object.freeze({productionUploadImplementationAvailable:true,productionDownloadImplementationAvailable:true,firestoreMembershipWriteProtectionConfirmed:firestore,productionRulesConfirmedDeployed:rules});}});}
  function blockers(gates,membership,mode){const out=[];if(!membership?.valid)out.push("membershipInvalid");if(membership?.active!==true)out.push("membershipInactive");if(!(mode==="upload"?UPLOAD_ROLES:READ_ROLES).includes(membership?.role))out.push("roleNotAuthorized");if(!gates.firestoreMembershipWriteProtectionConfirmed)out.push("firestoreMembershipWriteProtectionUnconfirmed");if(!gates.productionRulesConfirmedDeployed)out.push("productionRulesDeploymentUnconfirmed");if(mode==="upload"&&!gates.productionUploadImplementationAvailable)out.push("uploadImplementationUnavailable");if(mode!=="upload"&&!gates.productionDownloadImplementationAvailable)out.push("downloadImplementationUnavailable");return [...new Set(out)];}
  function safeName(name,foundation){const normalized=foundation.normalizeSafeFileName(String(name||""));const dot=normalized.lastIndexOf(".");if(dot<1)return "";return `${normalized.slice(0,dot)}.${normalized.slice(dot+1).toLowerCase()}`;}
  function validateLocalFile(file,foundation){const reasons=[];if(!file||typeof file.arrayBuffer!=="function")reasons.push("fileRequired");const originalName=String(file?.name||"");const normalized=safeName(originalName,foundation);const extension=normalized.split(".").pop();if(!normalized||!TYPES[extension])reasons.push("extensionNotAllowed");if(!Number.isSafeInteger(file?.size)||file.size<1||file.size>MAX_FILE_SIZE_BYTES)reasons.push("fileSizeInvalid");if(!TYPES[extension]?.includes(String(file?.type||"")))reasons.push("contentTypeInvalid");return{valid:reasons.length===0,reasons,originalName,safeFileName:normalized,extension,contentType:String(file?.type||"")};}
  async function sha256Hex(buffer,cryptoApi){const digest=await cryptoApi.subtle.digest("SHA-256",buffer);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("");}
  function randomFileId(cryptoApi){const bytes=new Uint8Array(16);cryptoApi.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");}
  function validateCloudMetadata(m,foundation){const keys=["schemaVersion","workspaceId","jobId","fileId","originalName","safeFileName","extension","contentType","sizeBytes","storagePath","sha256","status","createdBy","createdAtISO"];const reasons=[];if(!exactKeys(m,keys)||Object.keys(m||{}).length!==keys.length)reasons.push("metadataSchemaInvalid");try{if(m.storagePath!==foundation.storagePath(m.workspaceId,m.jobId,m.fileId,m.safeFileName))reasons.push("storagePathMismatch");}catch(_){reasons.push("storagePathInvalid");}if(m.schemaVersion!==1)reasons.push("schemaVersionInvalid");if(!TYPES[m.extension]?.includes(m.contentType))reasons.push("typeMismatch");if(!Number.isSafeInteger(m.sizeBytes)||m.sizeBytes<1||m.sizeBytes>MAX_FILE_SIZE_BYTES)reasons.push("sizeInvalid");if(!/^[a-f0-9]{64}$/.test(m.sha256||""))reasons.push("checksumInvalid");if(m.status!=="ready")reasons.push("statusInvalid");if(!/^[A-Za-z0-9][A-Za-z0-9:_-]{0,127}$/.test(m.createdBy||""))reasons.push("createdByInvalid");if(!/^\d{4}-\d{2}-\d{2}T.*Z$/.test(m.createdAtISO||""))reasons.push("createdAtInvalid");return{valid:reasons.length===0,reasons:[...new Set(reasons)].sort()};}
  function customMetadata(m){return{schemaVersion:"1",workspaceId:m.workspaceId,jobId:m.jobId,fileId:m.fileId,originalName:m.originalName,safeFileName:m.safeFileName,extension:m.extension,contentType:m.contentType,sizeBytes:String(m.sizeBytes),sha256:m.sha256,createdBy:m.createdBy};}
  function storageMetadataMatches(actual,m){const custom=actual?.customMetadata||{};return actual?.fullPath===m.storagePath&&Number(actual?.size)===m.sizeBytes&&actual?.contentType===m.contentType&&Object.entries(customMetadata(m)).every(([k,v])=>custom[k]===v);}
  function createApi(env={},injected={}){const foundation=injected.foundation||env.Cfr04WorkspaceMetadata;const cryptoApi=injected.crypto||env.crypto;const gates=injected.gates||createSessionGates();const now=injected.now||(()=>new Date());let busy=false,lastUpload=null;
    async function upload(options={}){const r={stage:"preflight",stages:[],attempted:{storageUpload:false,firestoreJobCreate:false,firestoreFileCreate:false,cleanupDelete:false},completed:{storageUpload:false,firestoreJobCreate:false,firestoreFileCreate:false,cleanupDelete:false,cleanupAbsenceVerified:false},warnings:[],error:null,indeterminate:false,possibleOrphanPath:"",manualReviewRequired:false,fullStateSaveCalls:0,protectedStateMutations:0};const enter=s=>{r.stage=s;r.stages.push(s);};const finish=()=>{lastUpload=safeResult(r);busy=false;return r;};if(busy){r.error={code:"concurrentUploadBlocked",message:"Another cutting-file upload is active."};return r;}busy=true;let objectRef=null,metadata=null;
      try{enter("preflight");const g=gates.get();enter("membership_validation");const blocked=blockers(g,options.membership,"upload");if(blocked.length)throw Object.assign(new Error(blocked.join(",")),{code:blocked[0]});enter("job_validation");if(!foundation.validateJobId(options.jobId).valid)throw Object.assign(new Error("Invalid job ID."),{code:"jobInvalid"});if(typeof options.jobExists!=="function"||!options.jobExists(options.jobId))throw Object.assign(new Error("Authoritative job not found."),{code:"jobNotFound"});
        enter("local_file_validation");const fv=validateLocalFile(options.file,foundation);if(!fv.valid)throw Object.assign(new Error(fv.reasons.join(",")),{code:fv.reasons[0]});enter("sha256_calculation");const bytes=await options.file.arrayBuffer();if(bytes.byteLength!==options.file.size)throw Object.assign(new Error("File size changed."),{code:"fileSizeChanged"});const sha256=await sha256Hex(bytes,cryptoApi);enter("immutable_path_creation");const fileId=randomFileId(cryptoApi),storagePath=foundation.storagePath(options.workspaceId,options.jobId,fileId,fv.safeFileName),createdAtISO=now().toISOString();metadata={schemaVersion:1,workspaceId:options.workspaceId,jobId:options.jobId,fileId,originalName:fv.originalName,safeFileName:fv.safeFileName,extension:fv.extension,contentType:fv.contentType,sizeBytes:options.file.size,storagePath,sha256,status:"ready",createdBy:options.uid,createdAtISO};if(!validateCloudMetadata(metadata,foundation).valid)throw Object.assign(new Error("Generated metadata invalid."),{code:"generatedMetadataInvalid"});objectRef=options.storage.ref(storagePath);
        enter("storage_upload");r.attempted.storageUpload=true;const existing=await objectRef.getMetadata().then(()=>true,e=>e?.code==="storage/object-not-found"?false:Promise.reject(e));if(existing)throw Object.assign(new Error("Immutable object already exists."),{code:"objectExists"});try{await objectRef.put(options.file,{contentType:metadata.contentType,customMetadata:customMetadata(metadata)});r.completed.storageUpload=true;}catch(e){if(!definite(e)){r.indeterminate=true;r.possibleOrphanPath=storagePath;r.manualReviewRequired=true;}throw e;}
        enter("uploaded_metadata_verification");if(!storageMetadataMatches(await objectRef.getMetadata(),metadata))throw Object.assign(new Error("Uploaded metadata mismatch."),{code:"uploadedMetadataMismatch"});enter("firestore_metadata_creation");const jobRef=options.firestore.doc(foundation.jobPath(options.workspaceId,options.jobId)),fileRef=options.firestore.doc(foundation.filePath(options.workspaceId,options.jobId,fileId));const jobExisting=await jobRef.get();if(!jobExisting.exists){r.attempted.firestoreJobCreate=true;await jobRef.set({schemaVersion:1,workspaceId:options.workspaceId,jobId:options.jobId,authoritativeStatePath:`workspaces/${options.workspaceId}/app/state`,createdAtISO},{merge:false});r.completed.firestoreJobCreate=true;}const fileExisting=await fileRef.get();if(fileExisting.exists)throw Object.assign(new Error("File metadata already exists."),{code:"fileMetadataExists"});r.attempted.firestoreFileCreate=true;try{await fileRef.set(metadata,{merge:false});r.completed.firestoreFileCreate=true;}catch(e){if(!definite(e)){r.indeterminate=true;r.possibleOrphanPath=storagePath;r.manualReviewRequired=true;}throw e;}
        enter("final_verification");const finalSnap=await fileRef.get();if(!finalSnap.exists||!validateCloudMetadata(finalSnap.data(),foundation).valid||JSON.stringify(finalSnap.data())!==JSON.stringify(metadata))throw Object.assign(new Error("Final metadata verification failed."),{code:"finalVerificationFailed",indeterminate:true});enter("completed");return finish();
      }catch(e){r.error=errorInfo(e);if(e?.indeterminate===true){r.indeterminate=true;r.manualReviewRequired=true;if(metadata)r.possibleOrphanPath=metadata.storagePath;}const definitePreReferenceFailure=r.completed.storageUpload&&!r.indeterminate&&["uploaded_metadata_verification","firestore_metadata_creation"].includes(r.stage)&&!r.completed.firestoreFileCreate;if(definitePreReferenceFailure&&objectRef){r.attempted.cleanupDelete=true;try{await objectRef.delete();r.completed.cleanupDelete=true;try{await objectRef.getMetadata();r.manualReviewRequired=true;r.possibleOrphanPath=metadata.storagePath;}catch(absence){if(absence?.code==="storage/object-not-found")r.completed.cleanupAbsenceVerified=true;else{r.manualReviewRequired=true;r.possibleOrphanPath=metadata.storagePath;}}}catch(_){r.manualReviewRequired=true;r.possibleOrphanPath=metadata.storagePath;}}return finish();}}
    async function download(options={}){const g=gates.get(),blocked=blockers(g,options.membership,"download");if(blocked.length)return{completed:false,blockers:blocked};const snap=await options.fileDocRef.get();if(!snap.exists)return{completed:false,blockers:["fileMetadataMissing"]};const metadata=snap.data(),validation=validateCloudMetadata(metadata,foundation);if(!validation.valid)return{completed:false,blockers:validation.reasons};const downloadRef=options.storage.ref(metadata.storagePath);let blob;if(typeof downloadRef.getBlob==="function")blob=await downloadRef.getBlob();else{const transientUrl=await downloadRef.getDownloadURL();const response=await (options.fetch||env.fetch)(transientUrl);if(!response.ok)throw new Error(`Download failed with HTTP ${response.status}.`);blob=await response.blob();}if(blob.size!==metadata.sizeBytes)return{completed:false,blockers:["downloadSizeMismatch"]};const buffer=await blob.arrayBuffer();const parsed=options.previewParser?await options.previewParser(buffer,metadata):null;let opened=false;if(options.openObjectUrl){const url=options.URL.createObjectURL(blob);try{await options.openObjectUrl(url,metadata);opened=true;}finally{options.URL.revokeObjectURL(url);}}return{completed:true,metadata,parsed,opened};}
    function diagnostics(membership){const g=gates.get(),uploadBlockers=blockers(g,membership,"upload"),downloadBlockers=blockers(g,membership,"download");return{membershipPath:membership?.path||null,membershipValid:membership?.valid===true,membershipRole:membership?.role||null,membershipActive:membership?.active===true,...g,effectiveUploadReady:uploadBlockers.length===0,effectiveDownloadReady:downloadBlockers.length===0,uploadBlockers,downloadBlockers,lastUploadResult:safeResult(lastUpload),fullStateSaveCalls:0,protectedStateMutations:0,permanentDeletionAvailable:false};}
    return Object.freeze({upload,download,diagnostics,gates,validateLocalFile:(f)=>validateLocalFile(f,foundation),validateCloudMetadata:(m)=>validateCloudMetadata(m,foundation),sha256Hex:(b)=>sha256Hex(b,cryptoApi)});}
  return Object.freeze({MAX_FILE_SIZE_BYTES,TYPES,UPLOAD_ROLES,READ_ROLES,STAGES,createSessionGates,createApi});
});
