(function(root,factory){"use strict";const api=factory(root?.CuttingJobHistory||(typeof require==="function"?require("./cuttingJobHistory.js"):null));if(typeof module==="object"&&module.exports)module.exports=api;if(root)root.CuttingJobRepair=api;})(typeof globalThis!=="undefined"?globalThis:this,function(history){
  "use strict";
  const clone=value=>typeof structuredClone==="function"?structuredClone(value):JSON.parse(JSON.stringify(value));
  const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),key=value=>String(value||"").trim().toLocaleLowerCase();
  const exact=(folders,name)=>folders.filter(folder=>key(folder?.name)===key(name));
  function plan(state,folders){
    const nextFolders=clone(folders||[]),created=[],renamed=[],reused=[];
    if(!nextFolders.some(folder=>String(folder?.id)===history.ROOT_ID))nextFolders.unshift({id:history.ROOT_ID,name:"All Jobs",parent:null,order:1});
    for(const[project,name]of history.PROJECT_CATEGORIES){let matches=exact(nextFolders,name);if(matches.length>1)return{ok:false,error:`Duplicate canonical category ${name}.`};let folder=matches[0];if(!folder){const reversed=nextFolders.filter(item=>history.reversedProject(item?.name)===project);if(reversed.length>1)return{ok:false,error:`Ambiguous reversed category for ${project}.`};folder=reversed[0];if(folder){renamed.push({id:String(folder.id),from:folder.name,to:name});folder.name=name;}}if(!folder){let id=`job_project_${project.toLocaleLowerCase()}`,suffix=1;while(nextFolders.some(item=>String(item.id)===id))id=`job_project_${project.toLocaleLowerCase()}_${++suffix}`;folder={id,name,parent:history.ROOT_ID,order:nextFolders.length+1};nextFolders.push(folder);created.push(String(id));}else reused.push(String(folder.id));folder.parent=history.ROOT_ID;}
    const nextActive=clone(state?.cuttingJobs||[]),nextCompleted=clone(state?.completedCuttingJobs||[]),assignments=[];
    for(const job of [...nextActive,...nextCompleted]){const resolution=history.resolveProjectCategory(job.projectNumber,nextFolders);if(resolution.status!=="matched")return{ok:false,error:resolution.reason};const from=job.cat??null,to=String(resolution.folder.id);job.cat=to;assignments.push({id:String(job.id),projectNumber:String(job.projectNumber),from,to});}
    const resequence=history.resequence(nextActive,nextCompleted);return{ok:true,nextFolders,nextActive,nextCompleted,created,renamed,reused,assignments,resequence};
  }
  function audit(state,folders){const p=plan(state,folders);return{...history.audit(state,folders),repairPlan:p.ok?{created:p.created,renamed:p.renamed,reused:p.reused,assignments:p.assignments,resequence:p.resequence}:null,blockingError:p.ok?"":p.error};}
  async function repair(env){const result={backupCreated:false,saveAttempted:false,saveCompleted:false,saveIndeterminate:false,rollbackAttempted:false,rollbackVerified:false,error:"",auditBefore:null,createdCategoryIds:[],renamedCategories:[],assignments:[],resequence:null},state=env.state();result.auditBefore=audit(state,env.categories());if(result.auditBefore.blockingError){result.error=result.auditBefore.blockingError;return result;}if(await env.revalidateBaseline()!==true){result.error="Latest authoritative cloud baseline revalidation failed.";return result;}const p=plan(state,env.categories());if(!p.ok){result.error=`Category revalidation failed: ${p.error}`;return result;}const before={active:clone(state.cuttingJobs||[]),completed:clone(state.completedCuttingJobs||[]),folders:clone(env.categories())};try{await env.backup();result.backupCreated=true;env.setCategories(p.nextFolders);state.cuttingJobs=p.nextActive;state.completedCuttingJobs=p.nextCompleted;result.createdCategoryIds=p.created;result.renamedCategories=p.renamed;result.assignments=p.assignments;result.resequence=p.resequence;result.saveAttempted=true;const saved=await env.saveCloudNow();result.saveCompleted=saved?.saved===true&&saved?.stateWriteCompleted===true;result.saveIndeterminate=!result.saveCompleted&&(saved?.indeterminate===true||(saved?.stateWriteAttempted===true&&saved?.stateWriteCompleted!==true));if(result.saveCompleted||result.saveIndeterminate){result.auditAfter=audit(state,env.categories());return result;}throw new Error(saved?.error||"Authoritative save did not complete.");}catch(error){result.error=String(error?.message||error);if(!result.saveIndeterminate){result.rollbackAttempted=true;state.cuttingJobs=clone(before.active);state.completedCuttingJobs=clone(before.completed);env.setCategories(clone(before.folders));result.rollbackVerified=same(state.cuttingJobs,before.active)&&same(state.completedCuttingJobs,before.completed)&&same(env.categories(),before.folders);}return result;}}
  return Object.freeze({plan,audit,repair});
});
