"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),factory=require("../js/cfr05CloudCuttingFiles.js"),foundation=require("../js/cfr04WorkspaceMetadata.js");
const tests=[],test=(n,f)=>tests.push([n,f]),now=()=>new Date("2026-08-13T12:00:00.000Z"),crypto=require("node:crypto").webcrypto;
const active=role=>({valid:true,active:true,role,path:"workspaces/github-prod/members/u1"});
function file(size=4){const bytes=new Uint8Array(size).fill(65);return{name:"part.dxf",type:"application/dxf",size,arrayBuffer:async()=>bytes.buffer};}
function harness(opts={}){const calls=[],docs=new Map(),objects=new Map();const gates=factory(globalThis).createSessionGates();if(opts.confirm!==false)gates.configureOperatorSession({firestoreMembershipWriteProtectionConfirmed:true,productionRulesConfirmedDeployed:true});const api=factory(globalThis).createApi(globalThis,{foundation,crypto,gates,now});
 const storage={ref(path){return{async getMetadata(){calls.push(`meta:${path}`);if(!objects.has(path))throw Object.assign(Error("not found"),{code:"storage/object-not-found"});return objects.get(path).meta;},async put(value,options){calls.push(`put:${path}`);if(opts.uploadError)throw opts.uploadError;objects.set(path,{blob:value,meta:{fullPath:path,size:value.size,contentType:options.contentType,customMetadata:options.customMetadata}});},async delete(){calls.push(`delete:${path}`);objects.delete(path);},async getBlob(){calls.push(`blob:${path}`);return objects.get(path).blob;}};}};
 const firestore={doc(path){return{async get(){calls.push(`get:${path}`);return{exists:docs.has(path),data:()=>docs.get(path)};},async set(value){calls.push(`set:${path}`);if(opts.firestoreError&&path.includes("/files/"))throw opts.firestoreError;docs.set(path,value);}};}};
 return{api,gates,calls,docs,objects,storage,firestore,options:{uid:"u1",workspaceId:"github-prod",jobId:"job_1",file:file(),membership:active("operator"),storage,firestore,jobExists:()=>true}};}
test("roles, missing invalid inactive membership and gates fail closed",async()=>{for(const role of ["owner","admin","operator"]){const h=harness();assert.equal((await h.api.upload({...h.options,membership:active(role)})).stage,"completed");}for(const role of ["viewer","unknown"]){const h=harness();assert.equal((await h.api.upload({...h.options,membership:active(role)})).error.code,"roleNotAuthorized");}for(const membership of [null,{valid:false,active:true,role:"operator"},{valid:true,active:false,role:"operator"}]){const h=harness();assert.notEqual((await h.api.upload({...h.options,membership})).stage,"completed");}const h=harness({confirm:false});let r=await h.api.upload(h.options);assert.equal(r.error.code,"firestoreMembershipWriteProtectionUnconfirmed");h.gates.configureOperatorSession({firestoreMembershipWriteProtectionConfirmed:true});r=await h.api.upload(h.options);assert.equal(r.error.code,"productionRulesDeploymentUnconfirmed");});
test("file validation maximum boundary, invalid content and paths",()=>{const h=harness();assert.equal(h.api.validateLocalFile(file(factory(globalThis).MAX_FILE_SIZE_BYTES)).valid,true);assert.equal(h.api.validateLocalFile(file(factory(globalThis).MAX_FILE_SIZE_BYTES+1)).valid,false);assert.equal(h.api.validateLocalFile({...file(),name:"../x.exe",type:"text/html"}).valid,false);assert.throws(()=>foundation.storagePath("github-prod","../job","id","part.dxf"));});
test("checksum is deterministic",async()=>assert.equal(await harness().api.sha256Hex(new TextEncoder().encode("abc")),"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"));
test("successful create-only upload verifies metadata without full-state calls",async()=>{const h=harness();globalThis.saveCloudNow=()=>{throw Error("must not call")};globalThis.snapshotState=globalThis.saveCloudNow;const r=await h.api.upload(h.options);assert.equal(r.stage,"completed");assert.equal(r.fullStateSaveCalls,0);assert.equal(r.protectedStateMutations,0);assert.equal(h.calls.filter(x=>x.startsWith("put:")).length,1);assert.equal(h.calls.filter(x=>x.includes("set:workspaces/github-prod/cuttingJobs/job_1/files/")).length,1);});
test("definite and indeterminate upload failures never retry",async()=>{let h=harness({uploadError:Object.assign(Error("denied"),{code:"storage/unauthorized"})}),r=await h.api.upload(h.options);assert.equal(r.indeterminate,false);assert.equal(h.calls.filter(x=>x.startsWith("put:")).length,1);h=harness({uploadError:Object.assign(Error("network unknown"),{indeterminate:true})});r=await h.api.upload(h.options);assert.equal(r.indeterminate,true);assert.equal(r.manualReviewRequired,true);assert.equal(h.calls.some(x=>x.startsWith("delete:")),false);});
test("definite Firestore failure cleans once; indeterminate leaves orphan for review",async()=>{let h=harness({firestoreError:Object.assign(Error("denied"),{code:"permission-denied"})}),r=await h.api.upload(h.options);assert.equal(h.calls.filter(x=>x.startsWith("delete:")).length,1);assert.equal(r.completed.cleanupAbsenceVerified,true);h=harness({firestoreError:Object.assign(Error("network unknown"),{indeterminate:true})});r=await h.api.upload(h.options);assert.equal(r.indeterminate,true);assert.equal(h.calls.some(x=>x.startsWith("delete:")),false);});
test("metadata mismatch is rejected",()=>{const h=harness();assert.equal(h.api.validateCloudMetadata({storagePath:"wrong"}).valid,false);});
test("download hands bounded buffer to parser and revokes object URL",async()=>{const h=harness(),up=await h.api.upload(h.options),path=up.possibleOrphanPath||[...h.objects.keys()][0],metadata=[...h.docs.entries()].find(([k])=>k.includes("/files/"))[1];let parsed=false,revoked=false;const r=await h.api.download({membership:active("viewer"),fileDocRef:{get:async()=>({exists:true,data:()=>metadata})},storage:h.storage,previewParser:async(buffer)=>{parsed=buffer.byteLength===4;return"preview";},openObjectUrl:async()=>{},URL:{createObjectURL:()=>"blob:temporary",revokeObjectURL:u=>{revoked=u==="blob:temporary";}}});assert.equal(r.completed,true);assert.equal(parsed,true);assert.equal(revoked,true);assert.equal(path,metadata.storagePath);});
test("concurrency blocks second upload and permanent deletion stays disabled",async()=>{const h=harness();let release;h.options.file.arrayBuffer=()=>new Promise(resolve=>{release=()=>resolve(new Uint8Array(4).buffer);});const first=h.api.upload(h.options);await Promise.resolve();const second=await h.api.upload(h.options);assert.equal(second.error.code,"concurrentUploadBlocked");release();await first;assert.equal(h.api.diagnostics(active("operator")).permanentDeletionAvailable,false);});
test("no cache/file-content persistence and rules are narrowly default deny",()=>{const source=fs.readFileSync("js/cfr05CloudCuttingFiles.js","utf8"),rules=fs.readFileSync("storage.rules","utf8");assert.equal(/localStorage|cutting_job_files_v1|saveCloudNow|snapshotState/.test(source),false);for(const required of ["allow update, list: if false","match /{allPaths=**} { allow read, write: if false; }","request.resource.size <= 52428800","['owner','admin','operator']","resource.metadata.createdBy == request.auth.uid"])assert.ok(rules.includes(required));assert.equal(rules.includes("cfr03-tests"),false);});
(async()=>{for(const[n,f]of tests){await f();console.log(`ok - ${n}`);}console.log(`1..${tests.length}`);})().catch(e=>{console.error(e);process.exitCode=1;});
