"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs");
const rules=fs.readFileSync("firestore.rules","utf8"),storage=fs.readFileSync("storage.rules","utf8"),firebase=JSON.parse(fs.readFileSync("firebase.json","utf8"));
const checks=[
  ["firebase config retains both rule files",()=>{assert.equal(firebase.firestore.rules,"firestore.rules");assert.equal(firebase.storage.rules,"storage.rules");}],
  ["authoritative app state remains locked to the production UID",()=>{assert.ok(rules.includes("match /workspaces/github-prod/app/{document=**}"));assert.ok(rules.includes("request.auth.uid == 'GntsaU7i2tXdDf05ds8cws5dfi63'"));assert.ok(rules.includes("allow read, write: if authorized();"));assert.equal(rules.includes("allow read, write: if signedIn();"),false);}],
  ["another authenticated UID cannot satisfy production authorization",()=>{const authorization=rules.slice(rules.indexOf("function authorized"),rules.indexOf("function validWorkspaceId"));assert.ok(authorization.includes("request.auth != null"));assert.ok(authorization.includes("request.auth.uid == 'GntsaU7i2tXdDf05ds8cws5dfi63'"));assert.equal(authorization.includes("request.auth.uid != null"),false);}],
  ["workspace root metadata and app state retain their exact production scopes",()=>{assert.ok(rules.includes("match /workspaces/github-prod {"));assert.ok(rules.includes("allow get, create, update: if authorized();"));assert.ok(rules.includes("allow delete: if false;"));assert.ok(rules.includes("match /workspaces/github-prod/app/{document=**}"));}],
  ["Firebase rules avoid rejected counted regex syntax",()=>{for(const rejected of ["{0,63}","{0,127}","{64}"]){assert.equal(rules.includes(rejected),false);assert.equal(storage.includes(rejected),false);}for(const text of ["id.size() <= 64","id.size() <= 128","data.sha256.size() == 64","request.resource.metadata.sha256.size() == 64","resource.metadata.sha256.size() == 64"])assert.ok((rules+storage).includes(text),text);}],
  ["membership is authorized-own-get only and client immutable",()=>{assert.ok(rules.includes("allow get: if authorized() && workspaceId == 'github-prod' && request.auth.uid == uid;"));assert.ok(rules.includes("allow list, create, update, delete: if false;"));}],
  ["membership validates exact bounded identity role and active state",()=>{for(const text of ["validMemberData","data.uid == uid","data.workspaceId == workspaceId","data.active == true","['owner','admin','operator','viewer']","hasOnly"])assert.ok(rules.includes(text));}],
  ["job and file metadata are create-only exact schemas",()=>{assert.ok(rules.includes("function validJob"));assert.ok(rules.includes("function validFile"));assert.ok(rules.includes("allow update, delete: if false;"));assert.ok(rules.includes("request.resource.data.createdBy == request.auth.uid"));}],
  ["atomic file create requires after-state compatibility job",()=>{assert.ok(rules.includes("existsAfter("));assert.ok(rules.includes("getAfter("));assert.ok(rules.includes("validJob(getAfter"));}],
  ["missing compatibility job is readable but list remains denied",()=>{assert.ok(rules.includes("activeMember(workspaceId) && (resource == null || validJob(resource.data, workspaceId, jobId))"));assert.ok(rules.includes("allow list: if false;"));}],
  ["existing cryptographic file document cannot be overwritten",()=>{const files=rules.slice(rules.indexOf("match /files/{fileId}"),rules.indexOf("match /logs/{logId}"));assert.ok(files.includes("allow create:"));assert.ok(files.includes("allow update, delete: if false;"));}],
  ["exact-job file get and list are split and membership gated",()=>{const files=rules.slice(rules.indexOf("match /files/{fileId}"),rules.indexOf("match /logs/{logId}"));assert.ok(files.includes("allow get: if activeMember(workspaceId) && validFile(resource.data, workspaceId, jobId, fileId);"));assert.ok(files.includes("allow list: if activeMember(workspaceId);"));assert.equal(files.includes("allow get, list:"),false);}],
  ["compatibility collection-group and unrelated lists stay denied",()=>{assert.ok(rules.includes("allow list: if false;"));assert.equal(rules.includes("/{path=**}/files/{fileId}"),false);assert.ok(rules.includes("match /logs/{logId} { allow read, write: if false; }"));assert.ok(rules.includes("match /{document=**} { allow read, write: if false; }"));}],
  ["default deny catches every unmatched path",()=>assert.ok(rules.includes("match /{document=**} { allow read, write: if false; }"))],
  ["canonical contract and exact identifiers are enforced",()=>{for(const text of ["application/dxf","application/octet-stream","data.fileId == fileId","data.jobId == jobId","data.workspaceId == workspaceId","data.sha256.matches","data.storagePath =="])assert.ok(rules.includes(text));}],
  ["Storage rules use canonical types and complete metadata",()=>{assert.equal(storage.includes("text/plain"),false);assert.equal(storage.includes("application/x-dxf"),false);for(const text of ["application/dxf","application/octet-stream","storagePath","status","createdAtISO","firestore.exists","allow update, list: if false"])assert.ok(storage.includes(text));}]
];
for(const[name,fn]of checks){fn();console.log(`ok - ${name}`);}console.log(`1..${checks.length}`);
