"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs");
const views=fs.readFileSync("js/views.js","utf8"),renderers=fs.readFileSync("js/renderers.js","utf8"),core=fs.readFileSync("js/core.js","utf8"),service=fs.readFileSync("js/cfr05CloudCuttingFiles.js","utf8");
const retired=["Attach from Reference Folder","Temporary local upload — not saved","Link OneDrive URL","Add from this computer OneDrive folder","OneDrive setup","data-job-file-add","data-upload-job","data-link-job-file","jobOneDriveLibraryAddBtn","data-job-onedrive-setup"];
for(const token of retired)assert.equal(views.includes(token),false,`retired view token: ${token}`);
assert.match(views,/id="jobSecureCloudFilesBtn">Upload secure cloud file/);
assert.match(views,/data-cloud-files=/);assert.match(views,/data-cloud-file-upload=/);
const uploadHandler=renderers.slice(renderers.indexOf('const cloudUpload = e.target.closest("[data-cloud-file-upload]")'),renderers.indexOf('return false;',renderers.indexOf('const cloudUpload = e.target.closest("[data-cloud-file-upload]")')));
assert.match(uploadHandler,/document\.body\.appendChild\(input\)/);
assert.match(uploadHandler,/await window\.uploadCfr05CuttingFile/);
assert.match(uploadHandler,/await window\.listCfr05CloudFiles\(jobId\)/);
assert.match(uploadHandler,/dataset\.cfr05LastResult/);
assert.equal(uploadHandler.includes("saveCloudNow"),false);
assert.match(uploadHandler,/cfr05LastUploadResult/);
assert.match(uploadHandler,/cfr05LastListingResult/);
assert.match(uploadHandler,/Upload succeeded; Cloud Files refresh failed\. Do not upload the file again\./);
assert.equal((uploadHandler.match(/uploadCfr05CuttingFile/g)||[]).length,1,"listing refresh must never retry the upload");
assert.match(renderers,/Cloud Files listing failed:/);
assert.match(renderers,/role="alert"/);
assert.match(renderers,/saved\?\.saved !== true \|\| saved\?\.stateWriteCompleted !== true/);
assert.match(renderers,/for \(const file of pendingCloudFiles\)/);
assert.match(renderers,/pendingNewJobFiles\.length = 0/);
assert.match(core,/firestore:FB\.db,onStage/);assert.match(service,/o\.onStage\?\.\(s,cleanResult\(r\)\)/);
console.log("ok - CFR-06 secure cutting-job UI wiring and legacy retirement");
