"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),factory=require("../js/cfr05CloudCuttingFiles.js"),foundation=require("../js/cfr04WorkspaceMetadata.js"),crypto=require("node:crypto").webcrypto;
const C=factory(globalThis),tests=[],test=(n,f)=>tests.push([n,f]),now=()=>new Date("2026-08-13T12:00:00.000Z"),active=role=>({valid:true,active:true,role,path:"workspaces/github-prod/members/u1"});
function file(ext="dxf",type="",size=4){const bytes=new Uint8Array(size).fill(65);return{name:`part.${ext}`,type,size,arrayBuffer:async()=>bytes.buffer};}
function harness(opts={}){const calls=[],docs=new Map(),objects=new Map(),gates=C.createSessionGates({location:{hostname:"test.vercel.app"}});gates.configureOperatorSession({confirmation:C.CONFIRMATION,hostname:"test.vercel.app",firestoreMembershipWriteProtectionConfirmed:true,firestoreFileAccessConfirmed:true,productionRulesConfirmedDeployed:true});
 const storage={ref(path){return{async getMetadata(){calls.push(`meta:${path}`);if(!objects.has(path))throw Object.assign(Error("not found"),{code:"storage/object-not-found"});return objects.get(path).meta;},async put(value,o){calls.push(`put:${path}`);if(opts.uploadError)throw opts.uploadError;objects.set(path,{bytes:await value.arrayBuffer(),meta:{fullPath:path,size:value.size,contentType:o.contentType,customMetadata:o.customMetadata}});},async delete(){calls.push(`delete:${path}`);objects.delete(path);},async getDownloadURL(){calls.push(`url:${path}`);return"https://secret.invalid/file?token=SECRET";}};}};
 const firestore={doc(path){return{path,async get(){calls.push(`get:${path}`);return{exists:docs.has(path),data:()=>docs.get(path)};}};},collection(path){return{async get(){calls.push(`query:${path}`);const found=[...docs].filter(([k])=>k.startsWith(`${path}/`));return{forEach(fn){found.forEach(([k,v])=>fn({id:k.split("/").pop(),data:()=>v}));}};}};},batch(){const pending=[];return{set(ref,value){pending.push([ref.path,value]);},async commit(){calls.push("batchCommit");if(opts.batchError)throw opts.batchError;pending.forEach(([k,v])=>docs.set(k,v));}};}};
 const fetch=opts.fetch||(async()=>({ok:true,status:200,headers:{get:()=>"4"},arrayBuffer:async()=>new Uint8Array(4).fill(65).buffer}));const api=C.createApi({fetch,AbortController,setTimeout,clearTimeout},{foundation,crypto,gates,now});return{api,gates,calls,docs,objects,storage,firestore,fetch,base:{uid:"u1",workspaceId:"github-prod",jobId:"job_1",file:file(),membership:active("operator"),storage,firestore,jobExists:()=>true}};}
test("exact Vercel confirmation gate and all authorization blockers",()=>{const g=C.createSessionGates({location:{hostname:"localhost"}});assert.equal(g.configureOperatorSession({confirmation:C.CONFIRMATION,hostname:"localhost",firestoreMembershipWriteProtectionConfirmed:true}).firestoreMembershipWriteProtectionConfirmed,false);assert.equal(g.configureOperatorSession({confirmation:"wrong",hostname:"x.vercel.app",firestoreMembershipWriteProtectionConfirmed:true}).firestoreMembershipWriteProtectionConfirmed,false);assert.equal(g.configureOperatorSession({confirmation:C.CONFIRMATION,hostname:"x.vercel.app",firestoreMembershipWriteProtectionConfirmed:true,firestoreFileAccessConfirmed:true,productionRulesConfirmedDeployed:true}).productionRulesConfirmedDeployed,true);});
test("empty MIME canonicalizes DXF ORD OMX; conflicts reject",()=>{const h=harness();for(const [ext,type] of [["dxf","application/dxf"],["ord","application/octet-stream"],["omx","application/octet-stream"]]){const v=h.api.validateLocalFile(file(ext,""));assert.equal(v.valid,true);assert.equal(v.contentType,type);}assert.equal(h.api.validateLocalFile(file("dxf","text/html")).valid,false);assert.equal(h.api.validateLocalFile(file("dxf","",C.MAX_FILE_SIZE_BYTES)).valid,true);assert.equal(h.api.validateLocalFile(file("dxf","",C.MAX_FILE_SIZE_BYTES+1)).valid,false);});
test("immutable create invokes put before any Storage read",async()=>{const h=harness(),r=await h.api.upload(h.base),storageCalls=h.calls.filter(x=>/^(put|meta|url|delete):/.test(x));assert.equal(r.stage,"completed");assert.match(storageCalls[0],/^put:/);assert.match(storageCalls[1],/^meta:/);assert.equal(storageCalls.filter(x=>x.startsWith("put:")).length,1);});
test("put authorization denial performs no cleanup or Firestore operation",async()=>{const denied=Object.assign(Error("unauthorized"),{code:"storage/unauthorized"}),h=harness({uploadError:denied}),r=await h.api.upload(h.base);assert.equal(r.stage,"storage_upload");assert.equal(r.attempted.storageUpload,true);assert.equal(r.completed.storageUpload,false);assert.equal(r.error.code,"storage/unauthorized");assert.equal(r.indeterminate,false);assert.equal(r.possibleOrphanPath,"");assert.equal(r.attempted.cleanupDelete,false);assert.equal(r.attempted.firestoreBatchCommit,false);assert.equal(h.calls.filter(x=>x.startsWith("put:")).length,1);assert.equal(h.calls.some(x=>x.startsWith("meta:")||x.startsWith("delete:")||x==="batchCommit"),false);});
test("first attachment reads only compatibility job then atomically creates job and file",async()=>{const h=harness(),r=await h.api.upload(h.base),commit=h.calls.indexOf("batchCommit"),beforeCommit=h.calls.slice(0,commit);assert.equal(r.stage,"completed");assert.equal(r.attempted.firestoreBatchCommit,true);assert.equal(r.completed.firestoreBatchCommit,true);const firestoreGets=beforeCommit.filter(x=>x.startsWith("get:"));assert.equal(firestoreGets.length,1);assert.equal(firestoreGets.some(x=>x.includes("/files/")),false);assert.equal(h.docs.has(foundation.jobPath("github-prod","job_1")),true);assert.equal([...h.docs.keys()].filter(x=>x.includes("/files/")).length,1);});
test("later attachment reuses the exact validated compatibility job",async()=>{const h=harness();await h.api.upload(h.base);const jobPath=foundation.jobPath("github-prod","job_1"),jobBefore=structuredClone(h.docs.get(jobPath));const r=await h.api.upload({...h.base,file:file("ord")});assert.equal(r.stage,"completed");assert.deepEqual(h.docs.get(jobPath),jobBefore);assert.equal([...h.docs.keys()].filter(x=>x.includes("/files/")).length,2);assert.equal(h.calls.filter(x=>x==="batchCommit").length,2);});
test("atomic batch succeeds and new session exact per-job listing reloads",async()=>{const h=harness(),legacy=[{id:"job_1"}],before=JSON.stringify(legacy);const r=await h.api.upload(h.base);assert.equal(r.stage,"completed");assert.equal(h.calls.filter(x=>x==="batchCommit").length,1);const fresh=C.createApi({fetch:h.fetch,AbortController,setTimeout,clearTimeout},{foundation,crypto,gates:h.gates,now});const listed=await fresh.listJobFiles({workspaceId:"github-prod",jobId:"job_1",membership:active("viewer"),firestore:h.firestore});assert.equal(listed.cloudFileCount,1);assert.equal(h.calls.filter(x=>x==="query:workspaces/github-prod/cuttingJobs/job_1/files").length,1);assert.equal(JSON.stringify(legacy),before);});
test("invalid listing metadata rejected and phone session needs no cache",async()=>{const h=harness();h.docs.set("workspaces/github-prod/cuttingJobs/job_1/files/bad",{jobId:"other"});const result=await h.api.listJobFiles({workspaceId:"github-prod",jobId:"job_1",membership:active("viewer"),firestore:h.firestore});assert.equal(result.cloudFileCount,0);assert.equal(result.rejectedMetadataDocumentCount,1);assert.ok(result.rejectedMetadataReasons[0].reasons.length);});
test("existing compatibility mismatch refuses and cleans",async()=>{const h=harness();h.docs.set(foundation.jobPath("github-prod","job_1"),{schemaVersion:1,workspaceId:"other"});const r=await h.api.upload(h.base);assert.equal(r.error.code,"compatibilityJobMismatch");assert.equal(h.calls.filter(x=>x.startsWith("delete:")).length,1);assert.equal(h.calls.includes("batchCommit"),false);});
test("definite batch failure is atomic and cleans exactly once",async()=>{const h=harness({batchError:Object.assign(Error("denied"),{code:"permission-denied"})}),r=await h.api.upload(h.base);assert.equal(h.docs.size,0);assert.equal(h.calls.filter(x=>x==="batchCommit").length,1);assert.equal(h.calls.filter(x=>x.startsWith("delete:")).length,1);const deletedAt=h.calls.findIndex(x=>x.startsWith("delete:"));assert.equal(h.calls.slice(deletedAt+1).filter(x=>x.startsWith("meta:")).length,1);assert.equal(r.completed.cleanupAbsenceVerified,true);});
test("indeterminate batch has no retry or deletion",async()=>{const h=harness({batchError:Object.assign(Error("network unknown"),{indeterminate:true})}),r=await h.api.upload(h.base);assert.equal(r.indeterminate,true);assert.equal(h.calls.filter(x=>x==="batchCommit").length,1);assert.equal(h.calls.some(x=>x.startsWith("delete:")),false);});
test("Firebase v8 getDownloadURL bounded fetch routes formats and revokes",async()=>{for(const ext of ["dxf","ord","omx"]){const h=harness(),up=await h.api.upload({...h.base,file:file(ext)}),entry=[...h.docs].find(([k])=>k.includes("/files/")),metadata=entry[1];let route,revoked=false;const r=await h.api.download({membership:active("viewer"),fileDocRef:{get:async()=>({exists:true,data:()=>metadata})},expected:{workspaceId:"github-prod",jobId:"job_1",fileId:metadata.fileId},storage:h.storage,fetch:h.fetch,AbortController,setTimeout,clearTimeout,previewDispatch:(x)=>{route=x;return"ok";},openObjectUrl:async()=>{},URL:{createObjectURL:()=>"blob:temp",revokeObjectURL:()=>{revoked=true;}}});assert.equal(r.completed,true);assert.equal(route,ext);assert.equal(revoked,true);assert.equal(h.calls.filter(x=>x.startsWith("url:")).length,1);assert.equal(JSON.stringify(r).includes("SECRET"),false);}});
test("download refuses Storage metadata and checksum mismatch",async()=>{const h=harness();await h.api.upload(h.base);const m=[...h.docs].find(([k])=>k.includes("/files/"))[1],ref=h.storage.ref(m.storagePath),saved=h.objects.get(m.storagePath).meta;h.objects.get(m.storagePath).meta={...saved,size:99};let r=await h.api.download({membership:active("viewer"),fileDocRef:{get:async()=>({exists:true,data:()=>m})},storage:h.storage,fetch:h.fetch,AbortController,setTimeout,clearTimeout});assert.deepEqual(r.blockers,["storageMetadataMismatch"]);h.objects.get(m.storagePath).meta=saved;const corrupt=async()=>({ok:true,status:200,headers:{get:()=>"4"},arrayBuffer:async()=>new Uint8Array([1,2,3,4]).buffer});r=await h.api.download({membership:active("viewer"),fileDocRef:{get:async()=>({exists:true,data:()=>m})},storage:h.storage,fetch:corrupt,AbortController,setTimeout,clearTimeout});assert.deepEqual(r.blockers,["downloadChecksumMismatch"]);});
test("compatibility document includes canonical createdBy",async()=>{const h=harness();await h.api.upload(h.base);const job=h.docs.get(foundation.jobPath("github-prod","job_1"));assert.equal(job.createdBy,"u1");assert.equal(h.api.validateCompatibilityJob(job,{workspaceId:"github-prod",jobId:"job_1"}).valid,true);assert.equal(h.api.validateCompatibilityJob({...job,extra:true},{workspaceId:"github-prod",jobId:"job_1"}).valid,false);});
test("HTTP network timeout size and metadata failures",async()=>{async function outcome(fetch){const h=harness({fetch});await h.api.upload(h.base);const m=[...h.docs].find(([k])=>k.includes("/files/"))[1];return h.api.download({membership:active("viewer"),fileDocRef:{get:async()=>({exists:true,data:()=>m})},storage:h.storage,fetch,AbortController,setTimeout,clearTimeout});}await assert.rejects(()=>outcome(async()=>({ok:false,status:403,headers:{get:()=>"0"}})),/HTTP 403/);await assert.rejects(()=>outcome(async()=>{throw Error("network")}),/network/);await assert.rejects(()=>outcome(async()=>({ok:true,headers:{get:()=>String(C.MAX_FILE_SIZE_BYTES+1)}})),/maximum/);const h=harness();const bad=await h.api.download({membership:active("viewer"),fileDocRef:{get:async()=>({exists:true,data:()=>({bad:true})})},storage:h.storage});assert.equal(bad.completed,false);});
test("no full-state/cache writes or permanent delete UI and strengthened rules",()=>{for(const p of ["js/cfr05CloudCuttingFiles.js"]){const s=fs.readFileSync(p,"utf8");assert.equal(/localStorage\.setItem/.test(s),false);}const views=fs.readFileSync("js/views.js","utf8"),rules=fs.readFileSync("storage.rules","utf8");assert.ok(views.includes("Cloud files"));assert.equal(views.includes("data-cloud-delete"),false);for(const x of ["omax-maintenance.firebasestorage.app","validExisting","allow update, list: if false","match /{allPaths=**} { allow read, write: if false; }"])assert.ok(rules.includes(x));assert.equal(rules.includes("cfr03-tests"),false);});
(async()=>{for(const[n,f]of tests){await f();console.log(`ok - ${n}`);}console.log(`1..${tests.length}`);})().catch(e=>{console.error(e);process.exitCode=1;});
