"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm");
const importer=require("../js/cuttingJobImporter")(),download=require("../js/cuttingJobImportDownload");
const core=fs.readFileSync("js/core.js","utf8"),adapter=core.slice(core.indexOf("function createCuttingJobImportPreviewTrace(){"),core.indexOf("const cuttingJobRepairBackup=")),start=core.indexOf("(function installCuttingJobImporterAdmin(){"),installer=core.slice(start,core.indexOf("\n})();",start)+6);
const root={id:"jobs_root",name:"All Jobs",parent:null,order:1};
const state=()=>({syncMeta:{rev:7},saveMeta:{status:"saved"},syncProcessLog:[],jobLayout:{},cuttingJobs:[],completedCuttingJobs:[],jobFolders:[structuredClone(root)],inventory:[{id:"keep",quantity:4}],maintenanceTasksV2:[{id:"maintenance",cost:10}],weeklyCostReports:[{id:"week",totalCutCost:123.45,generatedAtISO:"2026-10-02T19:52:35.090Z"}]});
const row={import_event_id:"cji02d",record_status:"active",job_name:"New cut",project_number:"1242",category:"Mesquite",material:"Steel",thickness_inches:".25",path_length_ft:"4",path_width_ft:"2",start_date:"2026-01-01",review_status:"reviewed"};
function stabilityHarness(options={}){
  const local=state(),cloud=state(),samples=[],calls=[];let loaded=7,version=0,reads=0,settles=0,snapshots=0;
  const env={snapshot:()=>{snapshots++;options.snapshot?.({local,cloud,snapshots});return structuredClone(local);},readCloud:async()=>{reads++;calls.push("read");options.read?.({local,cloud,reads,setLoaded:value=>loaded=value});return structuredClone(cloud);},loadedRevision:()=>loaded,localMutationVersion:()=>version,settle:async()=>{settles++;calls.push("settle");options.settle?.({local,cloud,settles,setLoaded:value=>loaded=value,setVersion:value=>version=value});},onSample:sample=>samples.push(sample)};
  return{local,cloud,samples,calls,env,run:()=>importer.stabilizePreviewBaseline(env),get reads(){return reads;},get settles(){return settles;},get snapshots(){return snapshots;}};
}
test("transient first comparison settles into consecutive exact cloud matches",async()=>{const h=stabilityHarness({settle:({local})=>delete local.jobLayout.fixtureRenderPhase});h.local.jobLayout.fixtureRenderPhase="pending";const before=structuredClone(h.cloud),r=await h.run();assert.deepEqual(r.baseline,before);assert.equal(r.revision,7);assert.equal(r.diagnostics.localSignatureChanged,true);assert.equal(r.diagnostics.firstMismatchPath,"$.jobLayout.fixtureRenderPhase");assert.equal(r.diagnostics.comparisonAttempts,2);assert.deepEqual(h.calls,["read","settle","settle","read"]);assert.equal(h.snapshots,3);assert.equal(h.samples.length,3);});
test("already stable state still checks a second authoritative read",async()=>{const h=stabilityHarness(),r=await h.run();assert.equal(r.diagnostics.status,"ready");assert.equal(r.diagnostics.localSignatureChanged,false);assert.equal(h.reads,2);assert.equal(h.settles,1);assert.equal(h.snapshots,3);});
const meaningful={cuttingJobs:s=>s.cuttingJobs.push({id:"edited"}),completedCuttingJobs:s=>s.completedCuttingJobs.push({id:"edited"}),jobFolders:s=>s.jobFolders[0].name="Edited",weeklyCostReports:s=>s.weeklyCostReports[0].totalCutCost++,inventory:s=>s.inventory[0].quantity++,maintenanceTasksV2:s=>s.maintenanceTasksV2[0].cost++};
for(const [field,mutate]of Object.entries(meaningful))test("persistent "+field+" business edit during preparation blocks",async()=>{const h=stabilityHarness({settle:({local,settles})=>{if(settles===1)mutate(local);}});await assert.rejects(h.run(),error=>{assert.match(error.message,/normalized business state differs/);assert.ok(error.previewPreparation.blockingMismatchPath.startsWith("$."+field));return true;});assert.equal(h.reads,2);assert.equal(h.settles,2);});
test("cloud business drift at unchanged revision cannot be adopted or retried",async()=>{const h=stabilityHarness({read:({cloud,local,reads})=>{if(reads===2){cloud.inventory[0].quantity++;local.inventory[0].quantity++;}}});await assert.rejects(h.run(),error=>{assert.match(error.message,/cloud business state changed/);assert.equal(error.previewPreparation.blockingMismatchPath,"$.inventory[0].quantity");return true;});assert.equal(h.reads,2);});
test("cloud revision change between reads blocks",async()=>{const h=stabilityHarness({read:({cloud,reads})=>{if(reads===2)cloud.syncMeta.rev++;}});await assert.rejects(h.run(),error=>{assert.match(error.message,/cloud revision changed/);assert.equal(error.previewPreparation.cloudRevision,8);assert.equal(error.previewPreparation.comparisonAttempts,2);return true;});});
test("loaded revision change during settling blocks even if business is identical",async()=>{const h=stabilityHarness({settle:({setLoaded})=>setLoaded(8)});await assert.rejects(h.run(),/loaded revision changed/);assert.equal(h.reads,1);assert.equal(h.settles,1);});
test("preview-start revision remains binding across parse/render",async()=>{const h=stabilityHarness();h.env.initialRevision=6;await assert.rejects(h.run(),/loaded revision changed/);assert.equal(h.reads,0);});
test("recorded business edit blocks even if its values were restored",async()=>{const h=stabilityHarness({settle:({setVersion})=>setVersion(1)});await assert.rejects(h.run(),/business edit was recorded/);assert.equal(h.reads,1);});
test("never-stabilizing local state stops after A/B/C and two bounded checks",async()=>{const h=stabilityHarness({snapshot:({local,snapshots})=>local.jobLayout.fixtureRenderPhase=snapshots});await assert.rejects(h.run(),error=>{assert.match(error.message,/consecutive snapshots did not stabilize/);assert.equal(error.previewPreparation.localSignatureChanged,true);assert.equal(error.previewPreparation.comparisonAttempts,2);assert.equal(error.previewPreparation.blockingMismatchPath,"$.jobLayout.fixtureRenderPhase");return true;});assert.equal(h.snapshots,3);assert.equal(h.reads,2);assert.equal(h.settles,2);});
test("read rejection has bounded diagnostics and no automatic retry",async()=>{const h=stabilityHarness();h.env.readCloud=async()=>{h.calls.push("rejected-read");throw Error("fixture rejection");};await assert.rejects(h.run(),error=>{assert.equal(error.previewPreparation.phase,"cloud-A");assert.match(error.message,/fixture rejection/);return true;});assert.deepEqual(h.calls,["rejected-read"]);});
test("comparison fingerprints do not decide equality",async()=>{const h=stabilityHarness();h.local.inventory[0].quantity=999;await assert.rejects(h.run(),/normalized business state differs/);assert.match(h.samples[0].fingerprint,/^[a-f0-9]{8}$/);assert.equal(Object.hasOwn(h.samples[0],"signature"),false);assert.equal(Object.hasOwn(h.samples[0],"data"),false);});

class Element{
  constructor(){this.listeners={};this.dataset={};this.disabled=false;this.checked=false;this.open=false;this.textContent="";this.innerHTML="";}
  addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}emit(name,event={isTrusted:true,preventDefault(){}}){return Promise.all((this.listeners[name]||[]).map(fn=>fn(event)));}showModal(){this.open=true;}close(){this.open=false;}focus(){}
}
function uiHarness(options={}){
  let cloud=state(),pending=!!options.transient,reads=0,frames=0,parses=0;const local=structuredClone(cloud),payloads=[],writes=[],clicks=[],timers=[],elements=Object.fromEntries(["Admin","Close","File","Preview","Reviewed","Run","Status","Rows","Confirm","ConfirmRun","ConfirmCancel","ConfirmMessage"].map(id=>[id,new Element()]));
  if(options.legacy){local.jobFolders.push({id:"job_project_0000",name:"0000 Undisclosed Project",projectNumber:null,parent:"jobs_root",order:2});local.cuttingJobs=Array.from({length:11},(_,i)=>({id:"old-"+i,projectNumber:"0000",cat:"job_project_0000",cutNumber:"C"+String(i+1).padStart(3,"0"),startISO:"2020-01-01"}));cloud=structuredClone(local);}
  const browser={Blob,navigator:{userActivation:{isActive:true}},URL:{createObjectURL:()=>"blob:fixture",revokeObjectURL:()=>clicks.push("dispose")},document:{body:{appendChild(){}},createElement:()=>({click(){assert.equal(browser.navigator.userActivation.isActive,true);clicks.push("download");},remove(){}})},setTimeout:fn=>{timers.push(fn);return timers.length;}};
  const materials=[{id:"steel",name:"Steel",density:.283,pricePerLb:.8}],window={CuttingJobImporter:importer,CuttingJobImportDownload:{...download,prepare:(name,data)=>{payloads.push(structuredClone(data));return download.prepare(name,data,browser);}},jobFolders:local.jobFolders,__loadedCloudRevisionForSaveGuard:7,__lastLoadedCloudState:structuredClone(cloud),getLiveJobMaterialSettings:()=>({materials,wasteFactor:10})};
  const context=vm.createContext({window,document:{getElementById:id=>elements[id.replace("cuttingJobImport","")]||null,addEventListener(){}},FB:{ready:true,user:{uid:"fixture"},docRef:{}},setTimeout,clearTimeout,structuredClone,cloneStructured:structuredClone,stableStringify:JSON.stringify,canWriteCloud:()=>!window.__autosaveDisabled,getCuttingJobImporterState:()=>local,localStorage:{getItem:()=>null},compactStateForStorage:value=>value,
    requestAnimationFrame:fn=>{const id=++frames;queueMicrotask(()=>{if(reads){pending=false;options.frame?.({local,cloud,frames});}fn();});return id;},cancelAnimationFrame(){},
    snapshotState:()=>{const value=structuredClone(local);if(pending)value.jobLayout.fixtureRenderPhase="pending";return value;},readCurrentCloudStateReadOnly:async()=>{reads++;browser.navigator.userActivation.isActive=false;options.read?.({local,cloud,reads});return structuredClone(cloud);},
    addJobFolder:name=>{const folder={id:"native-category",name,parent:"jobs_root",order:3};local.jobFolders.push(folder);return folder;},
    saveCloudNow:async args=>{assert.equal(args.expectedRevision,7);writes.push("save");cloud=structuredClone(local);cloud.syncMeta.rev=8;options.saved?.({cloud,local});return{saved:true,stateWriteAttempted:true,stateWriteCompleted:true};},renderRecoveryDiagnosticsPanel:()=>writes.push("suspend")});
  vm.runInContext(adapter+installer,context);
  const rows=options.rows||[{...row,...(options.legacy?{project_number:"0000",category:"Company Improvements"}:{})}];
  elements.File.files=[{name:"fixture.json",text:async()=>{parses++;if(options.parseGate)await options.parseGate;return JSON.stringify(rows);}}];
  return{local,window,context,elements,payloads,writes,clicks,get reads(){return reads;},get frames(){return frames;},get parses(){return parses;},get cloud(){return cloud;},preview:()=>elements.Preview.emit("click"),diagnostics:()=>JSON.parse(elements.Rows.dataset.lastPreviewPreparation),submit:async()=>{elements.Reviewed.checked=true;await elements.Reviewed.emit("change");await elements.Run.emit("click");browser.navigator.userActivation.isActive=true;await elements.ConfirmRun.emit("click");return JSON.parse(elements.Rows.dataset.lastImportResult);}};
}
test("actual Preview handler accepts a pending derived projection with one backup",async()=>{const h=uiHarness({transient:true}),before=structuredClone(h.cloud);await h.preview();assert.match(h.elements.Status.innerHTML,/Ready/);assert.equal(h.payloads.length,1);assert.deepEqual(h.payloads[0].inventory,before.inventory);assert.deepEqual(h.payloads[0].jobLayout,before.jobLayout);assert.equal(h.payloads[0].weeklyCostReports[0].generatedAtISO,before.weeklyCostReports[0].generatedAtISO);const d=h.diagnostics();assert.equal(d.status,"ready");assert.equal(d.firstMismatchPath,"$.jobLayout.fixtureRenderPhase");assert.equal(d.localSignatureChanged,true);assert.equal(d.comparisonAttempts,2);assert.equal(h.reads,2);assert.ok(d.samples.length<=10);assert.deepEqual(d.samples.slice(0,6).map(s=>s.phase),["preview-start","parsed","classified","rendered","definition-plan","prepare-entry"]);assert.deepEqual(h.writes,[]);});
test("one Preview produces one trusted download and one CAS guarded import",async()=>{const h=uiHarness({transient:true});await h.preview();const r=await h.submit();assert.equal(r.saveCompleted,true);assert.equal(r.verificationCompleted,true);assert.equal(h.payloads.length,1);assert.equal(h.clicks.filter(x=>x==="download").length,1);assert.deepEqual(h.writes,["save"]);assert.equal(h.cloud.cuttingJobs[0].projectNumber,"1242");});
test("genuine local mutation while queued frames settle still blocks Preview",async()=>{const h=uiHarness({frame:({local})=>local.inventory[0].quantity=9});await h.preview();assert.match(h.elements.Status.textContent,/Import stopped.*inventory/);assert.equal(h.diagnostics().status,"blocked");assert.equal(h.payloads.length,0);assert.equal(h.elements.Run.disabled,true);assert.equal(h.elements.Preview.disabled,false);assert.deepEqual(h.writes,[]);});
test("genuine cloud mutation during Preview blocks without adopting it",async()=>{const h=uiHarness({read:({cloud,reads})=>{if(reads===2)cloud.inventory[0].quantity=9;}});await h.preview();assert.match(h.elements.Status.textContent,/cloud business state changed/);assert.equal(h.local.inventory[0].quantity,4);assert.equal(h.payloads.length,0);});
test("never-stable Preview stops visibly and creates no backup",async()=>{const h=uiHarness({frame:({local,frames})=>local.jobLayout.fixtureRenderPhase=frames});await h.preview();assert.match(h.elements.Status.textContent,/consecutive snapshots did not stabilize/);assert.equal(h.diagnostics().comparisonAttempts,2);assert.equal(h.payloads.length,0);assert.equal(h.reads,2);assert.ok(h.frames<=4);});
test("double Preview and cancellation during parsing cannot start competing preparation",async()=>{let release;const parseGate=new Promise(resolve=>release=resolve),h=uiHarness({parseGate});h.elements.Admin.showModal();const first=h.preview();await h.preview();await h.elements.Admin.emit("cancel");assert.equal(h.elements.Admin.open,true);assert.equal(h.parses,1);release();await first;assert.equal(h.payloads.length,1);assert.equal(h.reads,2);});
test("legacy 0000 rename still shares a single prepared backup after stabilization",async()=>{const h=uiHarness({legacy:true,transient:true});await h.preview();assert.match(h.elements.Rows.innerHTML,/Rename existing/);const old=structuredClone(h.local.cuttingJobs),r=await h.submit();assert.equal(r.saveCompleted,true);assert.equal(h.local.jobFolders.filter(f=>f.id==="job_project_0000").length,1);assert.equal(h.local.jobFolders[1].name,"0000 Company Improvements");assert.deepEqual(h.local.cuttingJobs.slice(0,11),old);assert.equal(h.payloads[0].jobFolders[1].name,"0000 Undisclosed Project");});
test("explicit XXXX remains accepted after stabilized Preview",async()=>{const h=uiHarness({transient:true,rows:[{...row,project_number:"XXXX",category:"Undisclosed Project"}]});await h.preview();assert.equal((await h.submit()).saveCompleted,true);assert.equal(h.cloud.cuttingJobs[0].projectNumber,"XXXX");assert.equal(h.cloud.jobFolders[1].name,"XXXX Undisclosed Project");});
test("meaningful post-save drift still suspends after stabilized Preview",async()=>{const h=uiHarness({transient:true,saved:({cloud})=>cloud.weeklyCostReports[0].totalCutCost++});await h.preview();const r=await h.submit();assert.equal(r.saveIndeterminate,true);assert.equal(r.rollbackAttempted,false);assert.deepEqual(h.writes,["save","suspend"]);});
test("diagnostics expose paths and fingerprints without protected values",async()=>{const h=uiHarness();h.local.inventory[0].secret="DO-NOT-EXPOSE";await h.preview();const raw=h.elements.Rows.dataset.lastPreviewPreparation,d=h.diagnostics();assert.equal(raw.includes("DO-NOT-EXPOSE"),false);assert.equal(raw.includes('"inventory":'),false);assert.ok(d.firstMismatchPath.startsWith("$.inventory"));assert.ok(raw.length<4000);});
test("stabilization installs no recurring watcher and never calls a writer",()=>{const start=core.indexOf("function settleCuttingJobImportPreview(){"),end=core.indexOf("// Only receipts",start),source=core.slice(start,end);for(const forbidden of ["setInterval","MutationObserver","saveCloudNow","saveCloudDebounced","adoptState","renderJobs"]){assert.equal(source.includes(forbidden),false,forbidden);}const helper=importer.stabilizePreviewBaseline.toString();assert.equal(/\bwhile\s*\(|setInterval|MutationObserver/.test(helper),false);});
test("a stalled animation frame hits the explicit deadline and cancels callbacks",async()=>{const timers=new Map(),frames=new Map();let serial=0;const section=core.slice(core.indexOf("function settleCuttingJobImportPreview(){"),core.indexOf("// Only receipts",core.indexOf("function settleCuttingJobImportPreview(){"))),ctx=vm.createContext({setTimeout:(fn,ms)=>{const id=++serial;timers.set(id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id),requestAnimationFrame:fn=>{const id=++serial;frames.set(id,fn);return id;},cancelAnimationFrame:id=>frames.delete(id)});vm.runInContext(section+";this.settle=settleCuttingJobImportPreview",ctx);const pending=ctx.settle();await Promise.resolve();const watchdog=[...timers.values()].find(t=>t.ms===1000);watchdog.fn();await assert.rejects(pending,/within 1 second/);assert.equal(frames.size,0);assert.equal(timers.size,0);});
