"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm");
const history=require("../js/historicalImport"),firewall=require("../js/cuttingFileContentFirewall");
const initial=()=>({syncMeta:{rev:1},inventory:[{id:"part",qtyNew:9,qtyOld:3}],receiptTrackerWeeks:[],pumpEff:{baselineRPM:3500,baselineDateISO:"2026-01-01",entries:[{dateISO:"2026-01-01",rpm:3500,timeISO:"12:00"}],notes:[{dateISO:"2026-01-01",text:"keep",range:"all"}]},tasksInterval:[{id:"task",manualHistory:[]}],tasksAsReq:[],appConfig:{dailyHours:8},dashboardLayout:{keep:{x:4}},cuttingJobs:[],completedCuttingJobs:[]});
const purchase=(id="purchase-1")=>({import_event_id:id,source_id:"fixture-order",source_record_id:id,date:"2025-01-03",purchased:"Synthetic filter",cost:12.5,qty:2,partNumber:"0000",tax:1,shipping:3});
const pump=(id="pump-1",date="2026-02-03")=>({import_event_id:id,source_id:"fixture-rpm",source_record_id:id,date,rpm:3400,timeISO:"14:20"});
function harness(options={}){
  let local=initial(),cloud=structuredClone(local),loaded=1,saves=0,backups=0,suspended=false,reads=0;
  const env={state:()=>structuredClone(local),canWrite:()=>options.writable!==false,loadedRevision:()=>loaded,scan:firewall.scanCuttingFileContent,readCloud:async()=>{reads++;if(options.verifyReadFailure&&reads>1)throw Error("read unavailable");return structuredClone(cloud);},backup:async state=>{backups++;assert.deepEqual(state,cloud);if(options.backupFailure)throw Error("backup failed");return true;},apply:(key,value)=>{local[key]=value;},save:async()=>{saves++;if(options.save)return options.save;cloud={...structuredClone(local),syncMeta:{rev:2}};local.syncMeta={rev:2};loaded=2;if(options.verifyMismatch)cloud.receiptTrackerWeeks=[];return{saved:true,stateWriteCompleted:true};},suspend:()=>{suspended=true;}};
  const api=history.createApi(env);
  return{api,env,async submit(kind,rows){return api.submit(kind,rows,{confirmed:true,reviewedPreview:api.preview(kind,rows)});},get local(){return structuredClone(local);},get cloud(){return structuredClone(cloud);},get saves(){return saves;},get backups(){return backups;},get suspended(){return suspended;},alter(fn){fn(local,cloud);}};
}
test("purchase preview is non-mutating and reviewed append leaves quantities and unrelated history exact",async()=>{const h=harness(),before=h.local,rows=[purchase()];assert.equal(h.api.preview("purchase",rows)[0].status,history.STATUS.missing);assert.deepEqual(h.local,before);const result=await h.submit("purchase",rows);assert.equal(result.saved,true);assert.equal(result.verificationCompleted,true);assert.equal(result.beforeCount,0);assert.equal(result.afterCount,1);assert.deepEqual(h.cloud.inventory,before.inventory);assert.deepEqual(h.cloud.pumpEff,before.pumpEff);assert.deepEqual(h.cloud.tasksInterval,before.tasksInterval);assert.equal(h.cloud.receiptTrackerWeeks[0].rows[0].partNumber,"0000");assert.equal(h.cloud.receiptTrackerWeeks[0].rows[0].importProvenance.originalSourceDate,rows[0].date);assert.deepEqual(h.cloud.receiptTrackerWeeks[0].rows[0].importProvenance.sourceRecord,rows[0]);});
test("second execution of permanent IDs is a no-op with zero second write",async()=>{const h=harness(),rows=[purchase()];await h.submit("purchase",rows);assert.equal(h.api.preview("purchase",rows)[0].status,history.STATUS.present);const result=await h.submit("purchase",rows);assert.equal(result.importedIds.length,0);assert.equal(h.saves,1);assert.equal(h.backups,1);});
test("visible identical records with distinct permanent IDs remain distinct; untagged matches need review",async()=>{const h=harness();assert.equal((await h.submit("purchase",[purchase("a"),purchase("b")])).afterCount,2);h.alter((local,cloud)=>{for(const state of [local,cloud])state.receiptTrackerWeeks[0].rows[0].import_event_id=undefined;});assert.equal(h.api.preview("purchase",[purchase("c")])[0].status,history.STATUS.match);});
test("duplicate source identities never silently import either row",()=>{for(const kind of ["purchase","pump"]){const row=kind==="purchase"?purchase():pump();assert.ok(history.preview(kind,[row,{...row,date:"2025-02-04"}],initial()).every(item=>item.status===history.STATUS.problem));}});
test("malformed source dates/numbers and suspicious RPM remain review-required",()=>{for(const row of [{...purchase(),date:"2025-02-30"},{...purchase(),qty:"2"},{...purchase(),cost:-1}])assert.equal(history.preview("purchase",[row],initial())[0].status,history.STATUS.problem);for(const row of [{...pump(),rpm:0},{...pump(),rpm:3400.4},{...pump(),timeISO:"25:90"}])assert.equal(history.preview("pump",[row],initial())[0].status,history.STATUS.problem);});
test("pump compare-first never replaces surviving day or baseline/notes",async()=>{const h=harness(),before=h.local.pumpEff;assert.equal(h.api.preview("pump",[pump("same-day","2026-01-01")])[0].status,history.STATUS.match);const result=await h.submit("pump",[pump()]);assert.equal(result.saved,true);assert.deepEqual(h.cloud.pumpEff.entries[0],before.entries[0]);assert.equal(h.cloud.pumpEff.baselineRPM,before.baselineRPM);assert.deepEqual(h.cloud.pumpEff.notes,before.notes);assert.equal(h.cloud.pumpEff.entries[1].import_event_id,"pump-1");});
test("multiple new measurements per day are held for daily-model review",()=>{const rows=[pump("a"),pump("b")];assert.ok(history.preview("pump",rows,initial()).every(item=>item.status===history.STATUS.match));});
test("explicit confirmation and exact reviewed preview are required before backup or mutation",async()=>{const h=harness(),rows=[purchase()];assert.equal((await h.api.submit("purchase",rows)).saved,false);const result=await h.api.submit("purchase",rows,{confirmed:true,reviewedPreview:[]});assert.match(result.error,/preview/);assert.equal(h.backups,0);assert.equal(h.saves,0);});
test("definite write failure restores exact destination and leaves quantities untouched",async()=>{const h=harness({save:{saved:false,stateWriteAttempted:true,stateWriteCompleted:false,definiteFailure:true,indeterminate:false,error:"permission denied"}}),before=h.local;const result=await h.submit("purchase",[purchase()]);assert.equal(result.rollbackCompleted,true);assert.deepEqual(h.local,before);});
test("indeterminate completion never rolls back or retries and suspends writes",async()=>{const h=harness({save:{saved:false,stateWriteAttempted:true,stateWriteCompleted:false,indeterminate:true}});const result=await h.submit("pump",[pump()]);assert.equal(result.indeterminate,true);assert.equal(result.rollbackCompleted,false);assert.equal(h.saves,1);assert.equal(h.suspended,true);assert.equal(h.local.pumpEff.entries.length,2);});
test("post-save read failure or ID/count mismatch suspends writes without local rollback",async()=>{for(const options of [{verifyReadFailure:true},{verifyMismatch:true}]){const h=harness(options),result=await h.submit("purchase",[purchase()]);assert.equal(result.saved,false);assert.equal(result.saveCompleted,true);assert.equal(result.indeterminate,true);assert.equal(result.rollbackCompleted,false);assert.equal(h.suspended,true);}});
test("missing state, pending local drift, failed backup and embedded payload cannot stage imports",async()=>{for(const mode of ["missing","drift","backup","payload"]){const h=harness({backupFailure:mode==="backup"}),before=h.local;if(mode==="missing")h.alter((local,cloud)=>{delete cloud.syncMeta;});if(mode==="drift")h.alter(local=>local.inventory[0].qtyNew++);const row=mode==="payload"?{...purchase(),bytes:"data:application/dxf;base64,YQ=="}:purchase();const result=await h.submit("purchase",[row]);assert.equal(result.saved,false);assert.equal(h.saves,0);assert.equal(h.local.receiptTrackerWeeks.length,0);assert.deepEqual(h.local.pumpEff,before.pumpEff);}});
test("source ID composition is collision-free and ISO week 53/cross-year dates are retained",()=>{assert.notEqual(history.identity({source_id:"a|b",source_record_id:"c"}),history.identity({source_id:"a",source_record_id:"b|c"}));assert.equal(history.weekFor("2021-01-01").key,"2020-W53");assert.equal(history.weekFor("2025-01-03").startISO,"2024-12-30");});
test("real pump save merge preserves permanent IDs, provenance and existing notes",()=>{const source=fs.readFileSync("js/core.js","utf8"),section=source.slice(source.indexOf("function mergePumpEffForSave"),source.indexOf("function getTrackedStateSignature")),context=vm.createContext({normalizeDateISO:value=>value||null});vm.runInContext(section+";this.merge=mergePumpEffForSave",context);const imported={dateISO:"2026-02-03",rpm:3400,timeISO:"14:20",import_event_id:"stable",importProvenance:{sourceRecordId:"stable"}},merged=context.merge({entries:[imported]},initial().pumpEff);assert.equal(merged.entries[1].import_event_id,"stable");assert.equal(merged.entries[1].importProvenance.sourceRecordId,"stable");assert.equal(merged.entries[0].dateISO,"2026-01-01");});
