"use strict";
// Operator workflow on disposable localhost state only; every external request
// is blocked. Counts begin after deliberate fixture initialization.
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),http=require("node:http");
const {chromium}=require(process.env.OMAX_PLAYWRIGHT_PATH||"playwright");
const root=path.resolve(__dirname,".."),output=path.resolve(process.env.OMAX_CJO04B_OUTPUT||path.join(root,"artifacts/cjo04b"));
const types={".html":"text/html",".js":"text/javascript",".css":"text/css",".svg":"image/svg+xml",".json":"application/json"};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,"http://localhost").pathname),file=path.resolve(root,"."+pathname+(pathname.endsWith("/")?"index.html":""));if(!file.startsWith(root+path.sep)||pathname.split("/").some(part=>part.startsWith("."))){res.writeHead(403);res.end();return;}fs.readFile(file,(error,data)=>{res.writeHead(error?404:200,{"Content-Type":types[path.extname(file)]||"application/octet-stream","Cache-Control":"no-store"});res.end(error?"Not found":data);});});
const results=[];
async function main(){
  fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,".gitignore"),"*\n");
  await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const port=server.address().port,browser=await chromium.launch({channel:"msedge",headless:true});
  async function scenario(name,mode,run){
    const context=await browser.newContext({serviceWorkers:"block"}),page=await context.newPage(),errors=[];page.setDefaultTimeout(20000);page.on("pageerror",error=>errors.push(error.message));
    page.on("console",message=>{if(message.type()==="error"&&/chronolog|readCutLabel|resequence/i.test(message.text()))errors.push(message.text());});
    await context.route("**/*",route=>{const url=new URL(route.request().url());return url.hostname==="127.0.0.1"&&url.port===String(port)?route.continue():route.abort();});
    const capture=()=>page.evaluate(async()=>({state:await readCurrentCloudStateReadOnly(),counts:window.__cjo04Counts,live:{active:window.cuttingJobs,completed:window.completedCuttingJobs}}));
    try{
      await page.goto(`http://127.0.0.1:${port}/?devsafe=1`);await page.waitForFunction(()=>window.__initialAdoptComplete===true);
      await page.evaluate(async mode=>{
        if(!window.OMAXDevSafe.active)throw Error("Disposable backend required");location.hash="#/jobs";route();
        const job=(id,name,number,date,order)=>({id,name,cutNumber:number,cutDateISO:date,cutOrderWithinDay:order,projectNumber:"1241",cat:"fixture-project",startISO:date,dueISO:"2026-10-06",estimateHours:2,chargeRate:200,costRate:45,material:"Steel",materialCost:10,materialQty:1,priority:1,manualLogs:[],files:[],relatedCostId:"keep-"+id});
        window.cuttingJobs=[job("mon","Monday","C001","2026-10-05",1),job("thu","Thursday","C004","2026-10-08",1)];
        window.completedCuttingJobs=[job("tue","Tuesday","C002","2026-10-06",1),job("wed","Wednesday","C003","2026-10-07",1)];
        window.completedCuttingJobs.forEach(item=>{item.completedAtISO=item.cutDateISO;item.import_event_id="source-"+item.id;item.importProvenance={completed_date:"1900-01-01",sourceRowNumber:9};});
        if(mode==="same-day"){[window.cuttingJobs[0],...window.completedCuttingJobs].forEach((item,index)=>{item.cutDateISO="2026-10-05";item.cutOrderWithinDay=index+1;});}
        window.completedCuttingJobs[0].cat="other-project";window.completedCuttingJobs[0].projectNumber="1254";
        if(mode==="legacy"){for(const item of [...window.cuttingJobs,...window.completedCuttingJobs]){delete item.cutDateISO;delete item.cutOrderWithinDay;}for(let i=0;i<156;i++)window.completedCuttingJobs.push({id:"legacy-"+i,name:"Historical "+i,cat:"fixture-project",projectNumber:"1241",cutNumber:"C"+String(i+6).padStart(3,"0"),files:[],manualLogs:[]});}
        if(mode==="last-active"){window.cuttingJobs=window.cuttingJobs.filter(j=>j.id==="thu");window.cuttingJobs[0].manualLogs=[{dateISO:"2026-10-05",completedHours:1}];}
        cuttingJobs=window.cuttingJobs;completedCuttingJobs=window.completedCuttingJobs;setJobFolders([{id:"jobs_root",name:"All Jobs",parent:null,order:1},{id:"fixture-project",name:"1241 Lady Bird",parent:"jobs_root",order:2},{id:"other-project",name:"1254 Blanco",parent:"jobs_root",order:3}]);
        const saved=await saveCloudNow();if(!saved.saved)throw Error("Fixture save failed: "+JSON.stringify(saved));renderJobs();
        window.jobHistoryExpanded=true;renderJobs();window.__cjo04Before=await readCurrentCloudStateReadOnly();
      },mode);
      await armCounts(page,mode);
      const evidence=await run({page,capture});assert.deepEqual(errors,[]);
      const final=await capture();results.push({name,passed:true,counts:evidence?.counts||final.counts,diagnostics:evidence?.diagnostics,checks:evidence?.checks||["real Actions entry","date/placement input","preview/confirmation/cancel as applicable","asserted save counts and persisted state"],jobs:[...final.state.cuttingJobs,...final.state.completedCuttingJobs].map(job=>({id:job.id,label:job.cutNumber,date:job.cutDateISO,order:job.cutOrderWithinDay,auditRecords:job.cutChronologyHistory?.length||0})),pageErrors:errors});console.log("PASS "+name);
    }catch(error){console.error("SCENARIO "+name);console.error(errors);console.error(await page.evaluate(async()=>{const cloud=await readCurrentCloudStateReadOnly(),local=getCuttingJobChronologyLocalState();return{toasts:Array.from(document.querySelectorAll(".toast")).map(node=>node.textContent),active:window.cuttingJobs.map(job=>({id:job.id,name:job.name})),createForm:document.querySelector("#addJobForm")?.checkValidity(),difference:window.CuttingJobImporter.firstDifferencePath(cloud,local),fields:Object.keys(cloud).filter(key=>window.CuttingJobChronology.stateKey(cloud[key])!==window.CuttingJobChronology.stateKey(local[key])).map(key=>({key,cloud:JSON.stringify(cloud[key]).slice(0,450),local:JSON.stringify(local[key])?.slice(0,450)})),pending:hasPendingLocalChanges,canWrite:canWriteCloud("fixture"),loaded:window.__loadedCloudRevisionForSaveGuard,recovery:window.__recoveryReason,counts:window.__cjo04Counts};}));throw error;}
    finally{await context.close();}
  }
  try{
    for(const mode of ['canonical','writer-metadata'])await scenario('create/edit/complete/history edit/active copy with refresh at every step: '+mode,mode,async({page,capture})=>{
      let transactions=0,lastRevision=(await capture()).state.syncMeta.rev;
      const check=async()=>{await page.waitForFunction(()=>!isCuttingJobChronologySaving());const saved=await capture();assert.equal(saved.counts.authoritative,1);assert.equal(saved.counts.transactions,1);assert.equal(saved.counts.ordinary,0);assert.equal(saved.counts.debounce,0);assert.equal(await page.evaluate(()=>window.__recoveryInspectMode||window.__autosaveDisabled||Boolean(window.__lastIndeterminateSave)),false);assert.ok(saved.state.syncMeta.rev>lastRevision);assert.equal(await page.evaluate(()=>window.__loadedCloudRevisionForSaveGuard),saved.state.syncMeta.rev);lastRevision=saved.state.syncMeta.rev;transactions++;return saved;};
      const reload=async()=>{await page.reload();await page.waitForFunction(()=>window.__initialAdoptComplete===true);await page.evaluate(()=>{location.hash='#/jobs';window.jobHistoryExpanded=true;route();});await armCounts(page,mode);assert.equal(await page.evaluate(()=>window.__recoveryInspectMode),false);};
      await page.locator('[data-job-add-toggle]').click();await page.locator('#jobName').fill('CJO-04B lifecycle cut');await page.locator('#jobEst').fill('2');await page.locator('#jobStart').fill('2026-10-08');await page.locator('#jobDue').fill('2026-10-09');await page.locator('#jobCategory').selectOption('fixture-project');await page.locator('#addJobForm button[type="submit"]').click();await page.waitForFunction(()=>window.cuttingJobs.some(j=>j.name==='CJO-04B lifecycle cut'));const id=await page.evaluate(()=>window.cuttingJobs.find(j=>j.name==='CJO-04B lifecycle cut').id);await check();await reload();assert.ok((await capture()).live.active.some(j=>j.id===id));
      await normalEdit(page,id,false);await page.locator(`[data-j="startISO"][data-id="${id}"]`).fill('2026-10-04');await saveEdit(page,id,false);assert.equal((await check()).live.active.find(j=>j.id===id).startISO,'2026-10-04');await reload();assert.equal((await capture()).live.active.find(j=>j.id===id).cutNumber,'C001');
      await page.locator(`[data-job-actions-toggle="${id}"]`).click();await page.locator(`[data-complete-job="${id}"]`).click();await page.waitForFunction(id=>window.completedCuttingJobs.some(j=>j.id===id),id);await check();await reload();assert.ok((await capture()).live.completed.some(j=>j.id===id));assert.equal((await capture()).live.active.some(j=>j.id===id),false);
      await normalEdit(page,id,true);await page.locator(`[data-history-field="completedAtISO"][data-history-id="${id}"]`).fill('2026-10-04');await saveEdit(page,id,true);const earlier=await check();assert.equal(earlier.live.completed.find(j=>j.id===id).cutNumber,'C001');assert.equal(await categoryNumber(page,id),1);await reload();assert.equal((await capture()).live.completed.find(j=>j.id===id).completedAtISO,'2026-10-04');assert.ok((await historyIds(page)).indexOf(id)>(await historyIds(page)).indexOf('wed'));
      await normalEdit(page,id,true);await page.locator(`[data-history-field="completedAtISO"][data-history-id="${id}"]`).fill('2026-10-09');await saveEdit(page,id,true);const later=await check();assert.equal(later.live.completed.find(j=>j.id===id).cutNumber,'C005');assert.equal(await categoryNumber(page,id),4);await reload();assert.equal((await historyIds(page))[0],id);
      const original=(await capture()).live.completed.find(j=>j.id===id);await activeCopy(page,id);await page.waitForFunction(()=>window.cuttingJobs.some(j=>j.name==='CJO-04B lifecycle cut'));const copyId=await page.evaluate(()=>window.cuttingJobs.find(j=>j.name==='CJO-04B lifecycle cut').id);assert.notEqual(copyId,id);const copied=await check();assert.equal(copied.live.active.find(j=>j.id===copyId).startISO,'2026-10-10');for(const key of ['completedAtISO','actualHours','efficiency','cutDateISO','cutOrderWithinDay','status','completed'])assert.equal(Object.hasOwn(copied.live.active.find(j=>j.id===copyId),key),false,key);await reload();const final=await capture();assert.ok(final.live.active.some(j=>j.id===copyId));assert.ok(final.live.completed.some(j=>j.id===id));for(const key of ['id','name','startISO','completedAtISO','notes','files','manualLogs','cat','projectNumber'])assert.deepEqual(final.live.completed.find(j=>j.id===id)[key],original[key]);assert.equal(await page.locator('[data-edit-cut-chronology]').count(),0);await page.screenshot({path:path.join(output,'lifecycle-'+mode+'.png')});
      return{counts:{authoritative:transactions,transactions,ordinary:0,debounce:0},checks:['real Add Job + refresh','real normal Start Date Edit + refresh','Mark Complete same ID + refresh','Completion Date earlier/later + refresh and category/global/History changes','Make Active Copy new ID + original preserved + refresh','no Recovery Mode throughout','loaded revision advances each operation','one transaction per confirmed operation']};
    });
    await scenario('reproduce prior verifier false-indeterminate with writer-owned metadata','writer-metadata',async({page,capture})=>{
      const evidence=await page.evaluate(async priorSource=>{
        const fixed=window.CuttingJobChronology;eval(priorSource);const prior=window.CuttingJobChronology;window.CuttingJobChronology=fixed;
        let intent,committed;const api=prior.createMutationApi({canWrite:()=>true,localVersion:()=>({state:getCuttingJobChronologyLocalState()}),baselineMatches:source=>fixed.stateKey(source)===fixed.stateKey(getCuttingJobChronologyLocalState()),readState:readCurrentCloudStateReadOnly,
          prepareBusinessMutation:(source,operation,options)=>CuttingJobDateEditing.prepareMutation(source,operation,{...options,buildCompletedJob}),audit:()=>({operationId:'old-verifier-proof',atISO:'2026-10-06T12:00:00.000Z',actorUid:'fixture'}),writeState:async(next,revision,validate)=>{intent=structuredClone(next);const result=await writeAuthoritativeStateSnapshot(next,{merge:true},{expectedRevision:revision,validatePreparedState:validate});committed=structuredClone(result.committedState);return result;},adoptVerifiedState:()=>{throw Error('Prior verifier must refuse adoption');},suspend:()=>{}});
        const result=await api.save([],{expectedRevision:window.__loadedCloudRevisionForSaveGuard,businessOperation:{type:'edit',id:'thu',updates:{startISO:'2026-10-04'}}});const readback=await readCurrentCloudStateReadOnly();
        const strip=value=>Object.fromEntries(Object.entries(value).filter(([key])=>key!=='syncMeta'));
        return{saved:result.saved,verified:result.verified,indeterminate:result.indeterminate,requiresReload:result.requiresReload,stateWriteCompleted:result.stateWriteCompleted,authoritativeSaveCompleted:result.authoritativeSaveCompleted,prewriterVsCommitted:fixed.verificationDifferences(strip(intent),strip(committed)),committedVsReadback:fixed.verificationDifferences(fixed.durableStateProjection(committed),fixed.durableStateProjection(readback))};
      },fs.readFileSync(process.env.OMAX_CJO04B_PRIOR_SOURCE,'utf8'));
      assert.equal(evidence.saved,false);assert.equal(evidence.verified,false);assert.equal(evidence.indeterminate,true);assert.equal(evidence.requiresReload,true);assert.equal(evidence.authoritativeSaveCompleted,true);assert.equal(evidence.stateWriteCompleted,true);assert.equal(evidence.committedVsReadback.verificationMismatchCount,0);assert.ok(evidence.prewriterVsCommitted.verificationMismatchPaths.some(path=>path.startsWith('$.saveMeta')));
      return{counts:(await capture()).counts,checks:['exact prior coordinator loaded from starting PR head','old verifier reproduces committed-but-unverified flags','pre-writer mismatch paths are saveMeta','actual committed state and server readback match'],diagnostics:evidence};
    });
    await scenario('Make Active Copy Cancel has zero authoritative writes','canonical',async({page,capture})=>{const before=await capture();await page.locator('[data-history-actions-toggle="wed"]').click();await page.locator('[data-history-activate="wed"]').click();await page.locator('#makeActiveCopyModal [data-active-copy-cancel]').click();const after=await capture();assert.deepEqual(after.state,before.state);assert.equal(after.counts.authoritative,0);assert.equal(after.counts.transactions,0);});
    await scenario('Make Active Copy rejected transaction creates no phantom or success','canonical',async({page,capture})=>{const before=await capture();await page.evaluate(()=>{writeAuthoritativeStateSnapshot=async()=>{window.__cjo04Counts.authoritative++;return{saved:false,blocked:true,definiteFailure:true,stateWriteAttempted:false,stateWriteCompleted:false,error:'Copy transaction rejected'};};});await activeCopy(page,'wed');await page.waitForFunction(()=>window.__cjo04Counts.authoritative===1&&!isCuttingJobChronologySaving());const after=await capture();assert.deepEqual(after.state,before.state);assert.deepEqual(after.live,before.live);assert.equal(after.counts.transactions,0);assert.match(await page.locator('.toast').last().innerText(),/Copy transaction rejected/);});
    await scenario('real durable copy readback mismatch suspends with bounded evidence','canonical',async({page,capture})=>{
      const before=await capture();await page.evaluate(()=>{const get=FB.docRef.get.bind(FB.docRef);FB.docRef.get=async(...args)=>{const snap=await get(...args),cloud=snap.data();if(cloud.cuttingJobs.some(j=>String(j.id).startsWith('wednesday_'))){cloud.cuttingJobs=cloud.cuttingJobs.filter(j=>!String(j.id).startsWith('wednesday_'));return{...snap,data:()=>cloud};}return snap;};});await activeCopy(page,'wed');await page.waitForFunction(()=>Boolean(window.__lastIndeterminateSave));const after=await capture();assert.equal(after.counts.transactions,1);assert.deepEqual(after.live,before.live);const result=await page.evaluate(()=>window.__lastIndeterminateSave);assert.equal(result.verified,false);assert.equal(result.requiresReload,true);assert.ok(result.verificationMismatchPaths.includes('$.cuttingJobs.length'));assert.ok(result.verificationMismatchPaths.length<=16);assert.equal(await page.evaluate(()=>window.__recoveryInspectMode),true);
    });
  }finally{await browser.close();server.close();}
  fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({passed:results.length,failed:0,results},null,2));
}
async function normalEdit(page,id,completed){await page.locator((completed?'[data-history-actions-toggle="':'[data-job-actions-toggle="')+id+'"]').click();await page.locator((completed?'[data-history-edit="':'[data-edit-job="')+id+'"]').click();}
async function saveEdit(page,id,completed){await page.locator((completed?'[data-history-save="':'[data-save-job="')+id+'"]').click();await page.waitForFunction(({id,completed})=>!isCuttingJobChronologySaving()&&!document.querySelector((completed?'[data-history-save="':'[data-save-job="')+id+'"]'),{id,completed});}
async function activeCopy(page,id){await page.locator(`[data-history-actions-toggle="${id}"]`).click();await page.locator(`[data-history-activate="${id}"]`).click();await page.locator('#makeActiveCopyModal [data-active-copy-start]').fill('2026-10-10');await page.locator('#makeActiveCopyModal [data-active-copy-due]').fill('2026-10-11');await page.locator('#makeActiveCopyModal [data-active-copy-submit]').click();}
async function armCounts(page,mode){await page.evaluate(mode=>{
  window.__cjo04Counts={ordinary:0,debounce:0,authoritative:0,transactions:0};
  const save=saveCloudNow,debounce=saveCloudDebounced,write=writeAuthoritativeStateSnapshot,transaction=window.OMAXDevSafe.db.runTransaction;
  saveCloudNow=(...args)=>{window.__cjo04Counts.ordinary++;return save(...args);};saveCloudDebounced=(...args)=>{window.__cjo04Counts.debounce++;return debounce(...args);};writeAuthoritativeStateSnapshot=(...args)=>{window.__cjo04Counts.authoritative++;return write(...args);};
  window.OMAXDevSafe.db.runTransaction=callback=>{window.__cjo04Counts.transactions++;return transaction(tx=>callback({get:ref=>tx.get(ref),set:(ref,value,options)=>{if(mode==='writer-metadata'){value.saveMeta={...(value.saveMeta||{}),lastSaveStatus:'saved',lastSavedAt:new Date().toISOString()};}tx.set(ref,value,options);}}));};
},mode);}
const historyIds=page=>page.locator('[data-history-row]').evaluateAll(rows=>rows.map(row=>row.dataset.historyRow));
const categoryNumber=(page,id)=>page.evaluate(id=>CuttingJobDateEditing.categoryNumbers(cuttingJobs,completedCuttingJobs).get(id),id);
main().catch(error=>{server.close();console.error(error);process.exitCode=1;});
